{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "5b747fd2",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\HOANGD~1\\AppData\\Local\\Temp/ipykernel_5804/2709469272.py:3: UserWarning: \n",
      "The dash_core_components package is deprecated. Please replace\n",
      "`import dash_core_components as dcc` with `from dash import dcc`\n",
      "  import dash_core_components as dcc\n",
      "C:\\Users\\HOANGD~1\\AppData\\Local\\Temp/ipykernel_5804/2709469272.py:4: UserWarning: \n",
      "The dash_html_components package is deprecated. Please replace\n",
      "`import dash_html_components as html` with `from dash import html`\n",
      "  import dash_html_components as html\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "          Day  Time Mã Đối Chiếu Mã Khách Hàng                Mã NVKD  \\\n",
      "0  12/30/2021     7  E5977681285        500000                    NaN   \n",
      "1  12/30/2021     7  E9377686501        500000                    NaN   \n",
      "2  12/30/2021     7  E9777231923        290000                    NaN   \n",
      "3  12/30/2021     7  E7277341414      50C00359  50X00026 - Phan Bá Vũ   \n",
      "4  12/30/2021     7  E2176952447      50C00359  50X00026 - Phan Bá Vũ   \n",
      "\n",
      "    Tên Shop  Số Điện Thoại Shop        COD  Cước Vận Chuyển      status_type  \\\n",
      "0        NaN                 NaN        0.0           139000  Đang vận chuyển   \n",
      "1        NaN                 NaN        0.0            89000  Đang vận chuyển   \n",
      "2  988173230         988173230.0  9400000.0           225000  Đang vận chuyển   \n",
      "3  934475861         934475861.0   968000.0            15300   Chờ duyệt hoàn   \n",
      "4  934475861         934475861.0   843000.0            15300     Đã giao hàng   \n",
      "\n",
      "   ... Khối lượng Dài Rộng  Cao Khối lượng quy đổi Kho hiện tại  \\\n",
      "0  ...        1.0  33   22    6                1.0  Kho NTX.18X   \n",
      "1  ...        1.0  33   22    6                1.0  Kho NTX.18X   \n",
      "2  ...       10.0   0    0    0               10.0  Kho NTX.HAN   \n",
      "3  ...        1.0   1    1    1                0.0     HNI-MP06   \n",
      "4  ...        1.0   1    1    1                0.0     HNI-MP06   \n",
      "\n",
      "  TG nhập kho đầu tiên  TG nhập kho cuối TG sự cố nhận sau cùng  \\\n",
      "0      12/30/2021 7:52  12/30/2021 20:11                      0   \n",
      "1      12/30/2021 7:52  12/30/2021 20:11                      0   \n",
      "2      12/30/2021 8:56  12/30/2021 12:04       12/28/2021 17:13   \n",
      "3      12/30/2021 9:22  12/30/2021 17:10       12/29/2021 12:00   \n",
      "4      12/30/2021 9:00   12/30/2021 9:00       12/29/2021 12:00   \n",
      "\n",
      "  TG sự cố trả sau cùng  \n",
      "0                     0  \n",
      "1                     0  \n",
      "2                     0  \n",
      "3       12/30/2021 9:27  \n",
      "4      12/30/2021 10:07  \n",
      "\n",
      "[5 rows x 57 columns]\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      " * Serving Flask app '__main__' (lazy loading)\n",
      " * Environment: production\n",
      "\u001b[31m   WARNING: This is a development server. Do not use it in a production deployment.\u001b[0m\n",
      "\u001b[2m   Use a production WSGI server instead.\u001b[0m\n",
      " * Debug mode: on\n"
     ]
    }
   ],
   "source": [
    "import dash                     \n",
    "from dash.dependencies import Input, Output, State\n",
    "import dash_core_components as dcc\n",
    "import dash_html_components as html\n",
    "import plotly.express as px \n",
    "import pandas as pd     \n",
    "\n",
    "df = pd.read_csv(r\"C:\\Users\\Hoang Dao\\Desktop\\TEST.csv\")\n",
    "df[\"Time\"] = pd.to_datetime(df[\"Time\"])\n",
    "df[\"Time\"] = df[\"Time\"].dt.hour\n",
    "\n",
    "print(df.head())\n",
    "\n",
    "\n",
    "external_stylesheets = ['https://codepen.io/chriddyp/pen/bWLwgP.css']\n",
    "app = dash.Dash(__name__, external_stylesheets=external_stylesheets)\n",
    "\n",
    "app.layout = html.Div([\n",
    "    html.H1(\"Thống Kê Lấy Hàng\", style={\"textAlign\":\"center\"}),\n",
    "    html.Hr(),\n",
    "    html.P(\"Choose Delivery Status:\"),\n",
    "    html.Div(html.Div([\n",
    "      dcc.Dropdown(id='status-type', clearable=True,\n",
    "                     options=[{'label': x, 'value': x} for x in\n",
    "                     df[\"status_type\"].unique()],multi = True ),\n",
    "    ],className=\"two columns\"),className=\"row\"),\n",
    "\n",
    "    html.Div(id=\"output-div\", children=[]),\n",
    "])\n",
    "\n",
    "@app.callback(Output(component_id=\"output-div\", component_property=\"children\"),\n",
    "              Input(component_id=\"status-type\", component_property=\"value\"),)\n",
    "      \n",
    "def make_graphs(status_chosen):\n",
    "    # HISTOGRAM\n",
    "    df_hist = df[df[\"status_type\"]==status_chosen]\n",
    "    fig_hist = str (px.histogram(df_hist, x=\"status_type\"))\n",
    "    fig_hist.update_xaxes(categoryorder=\"total descending\")\n",
    "    \n",
    "    return [\n",
    "        html.Div([\n",
    "            html.Div([dcc.Graph(figure= str(fig_hist))], className=\"six columns\")]\n",
    "            ,className=\"row\"\n",
    "            )]\n",
    "\n",
    "if __name__ == '__main__':\n",
    "    app.run_server(debug=True, use_reloader=False)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
